--// Cmn65's Raiding Terminal -- Plugin Installer
--// Source Code -- Version 0.1-1
--// Very choppy and sketchy UI. I will be adjusting the open-source modules to my needs sooner or later! :)
--// Thank you to @ROBLOX for the StudioWidget UI collection. Without them I would have to make a very crappy library of Gui objects. Link: https://github.com/Roblox/StudioWidgets

print("Cmn65's Raiding Terminal plugin is loading...")

local toolbar = plugin:CreateToolbar("Cmn65's Group Raid Terminal")

local StudioWidgets = script.StudioWidgets

local CollapsibleTitledSection = require(StudioWidgets.CollapsibleTitledSection)
local CustomTestButton = require(StudioWidgets.CustomTextButton)
local GuiUtilities = require(StudioWidgets.GuiUtilities)
local ImageButtonWithTest = require(StudioWidgets.ImageButtonWithText)
local LabeledCheckbox = require(StudioWidgets.LabeledCheckbox)
local LabeledMultiChoice = require(StudioWidgets.LabeledMultiChoice)
local LabeledRadioButton = require(StudioWidgets.LabeledRadioButton)
local LabeledSlider = require(StudioWidgets.LabeledSlider)
local LabeledTextInput = require(StudioWidgets.LabeledTextInput)
local RbxGui = require(StudioWidgets.RbxGui)
local StatefullImageButton = require(StudioWidgets.StatefulImageButton)
local VerticallyScalingListFrame = require(StudioWidgets.VerticallyScalingListFrame)

local configButton = toolbar:CreateButton(1, "Right Click and click on 'Cmn65's Raid Terminal' to open the configuration", "rbxassetid://4902906761", "Right Click and click on 'Cmn65's Raid Terminal' to open the configuration")

local teamColorChoices = {
	{Id = "Black", Text = "Black"},
	{Id = "Bright blue", Text = "Blue"},
	{Id = "Bright yellow", Text = "Yellow"},
	{Id = "Bright green", Text = "Green"},
	{Id = "White", Text = "White"},
}

local CONFIGURATION_SOURCE_CODE = "--// Cmn65's Raiding Terminal\n-->> Configuration File\n-->> Edit this file to your needs and then have fun raiding!!\n\n-- See Documentation/Install for more detailed information\n\n-->> This configuration file as generated by the plugin! Make sure the configuration file is correct! \n\n\n\nlocal configuration = {"
local definedConfiguration = {
	['groupId'] = 1;
	['groupTeamName'] = "Defenders";
	['groupTeamColor'] = BrickColor.Green();
	['raiderTeamColor'] = BrickColor.Red();
	['allyTeamColor'] = BrickColor.new("Bright yellow");
	['adminRank'] = 200;
	['autoTeam'] = true;
	['allowRandoms'] = true;
	['bannedPlayers'] = {"Hacker!!"};
	['totalTime'] = 1800;
	['raidingTime'] = 630;
	['raidersNeeded'] = 0;
	['groupMembersNeeded'] = 0;
	['terminalPart'] = nil;
	['printConfiguration'] = false;
	['auto_update'] = true;
	['update_to_minor_versions'] = false;
	['AutoFix'] = true;
	['config_version'] = 2;
	['developer'] = false;
}







local widgetInfo = DockWidgetPluginGuiInfo.new( Enum.InitialDockState.Left, true, true,  -- Don't override the previous enabled state
	300,    -- X Default width of the floating window
	300,    -- Y Default height of the floating window
	
	300,    -- X Minimum width of the floating window
	300     -- Y Minimum height of the floating window
)
 
-- Create new widget GUI
local testWidget = plugin:CreateDockWidgetPluginGui("Cmn65's Raiding Terminal Plugin", widgetInfo)
testWidget.Title = "Cmn65's Group Raiding Terminal Configuration"  -- Optional widget title
local basicConfig = CollapsibleTitledSection.new("suffix", "Basic Configuration", true, true, false)
local developerConfig = CollapsibleTitledSection.new("suffix", "Developer Configuration", true, false, true)

local basicsettingsFrame = VerticallyScalingListFrame.new("suffix")

local WidgetObjects = {
	setting_groupID = LabeledTextInput.new("suffix", "Your Group's ID", "1");
	setting_groupName = LabeledTextInput.new("suffix", "Group Team Name", "Defenders");
	setting_groupTeamColor = LabeledMultiChoice.new("suffix", "Your Group's Team Color", teamColorChoices, 1);
	setting_adminRank = LabeledTextInput.new("suffix", "Admin Rank", "1 - 255");
	setting_autoTeam = LabeledCheckbox.new("suffix", "Auto-Team Players", true, false);
	setting_allowRandoms = LabeledCheckbox.new("suffix", "Allow Random Players", true, false);
	setting_totalTime = LabeledTextInput.new("suffix", "Total Raid Time", "time, in seconds");
	setting_raidTime = LabeledTextInput.new("suffix", "Raiding Time", "time to capture in seconds");
	setting_raidersNeeded = LabeledTextInput.new("suffix", "Min. Raiders", "3");
	setting_defendersNeeded = LabeledTextInput.new("suffix", "Min. Defenders", "5");
	setting_terminalPart = LabeledTextInput.new("suffix", "Terminal Object", "game.Workspace.TERMINAL");
	setting_auto_update = LabeledCheckbox.new("suffix", "Auto-Update", true, false);
	setting_AutoFix = LabeledCheckbox.new("suffix", "Auto-Fix Script", true, false);
	InjectTerminalButton = CustomTestButton.new("generateTerminal", "Click to INJECT Terminal");
	RemoveTerminalButton = CustomTestButton.new("generateTerminal", "Click to REMOVE Terminal");
}


WidgetObjects.InjectTerminalButton:GetButton().Size = UDim2.new(0,250,0,25)
WidgetObjects.RemoveTerminalButton:GetButton().Size = UDim2.new(0,250,0,25)
WidgetObjects.setting_groupID:SetMaxGraphemes(10)
WidgetObjects.setting_groupName:SetMaxGraphemes(30)
WidgetObjects.setting_adminRank:SetMaxGraphemes(3)
WidgetObjects.setting_totalTime:SetMaxGraphemes(5)
WidgetObjects.setting_raidTime:SetMaxGraphemes(5)
WidgetObjects.setting_raidersNeeded:SetMaxGraphemes(2)
WidgetObjects.setting_defendersNeeded:SetMaxGraphemes(2)
WidgetObjects.setting_terminalPart:SetMaxGraphemes(1000000)




basicsettingsFrame:AddChild(WidgetObjects.setting_groupID:GetFrame())
basicsettingsFrame:AddChild(WidgetObjects.setting_groupName:GetFrame())
basicsettingsFrame:AddChild(WidgetObjects.setting_groupTeamColor:GetFrame())
basicsettingsFrame:AddChild(WidgetObjects.setting_adminRank:GetFrame())
basicsettingsFrame:AddChild(WidgetObjects.setting_autoTeam:GetFrame())
basicsettingsFrame:AddChild(WidgetObjects.setting_allowRandoms:GetFrame())
basicsettingsFrame:AddChild(WidgetObjects.setting_totalTime:GetFrame())
basicsettingsFrame:AddChild(WidgetObjects.setting_raidTime:GetFrame())
basicsettingsFrame:AddChild(WidgetObjects.setting_raidersNeeded:GetFrame())
basicsettingsFrame:AddChild(WidgetObjects.setting_defendersNeeded:GetFrame())
basicsettingsFrame:AddChild(WidgetObjects.setting_terminalPart:GetFrame())
basicsettingsFrame:AddChild(WidgetObjects.setting_auto_update:GetFrame())
basicsettingsFrame:AddChild(WidgetObjects.setting_AutoFix:GetFrame())
basicsettingsFrame:AddChild(WidgetObjects.InjectTerminalButton:GetButton())
basicsettingsFrame:AddChild(WidgetObjects.RemoveTerminalButton:GetButton())


basicsettingsFrame:AddBottomPadding()
basicsettingsFrame:GetFrame().Parent = testWidget



function BUILD_SOURCE_CODE()
	warn(">>[SOURCE_CODE]: Building...")
	local bannedPlayersStr = "bannedPlayers = {"
	for key, value in pairs(definedConfiguration) do -- Format values for numbers and bools (easy)
		if string.find(key, "TeamColor") == nil and key ~= "bannedPlayers" then
			if string.find(key, "TeamName") ~= nil then CONFIGURATION_SOURCE_CODE = CONFIGURATION_SOURCE_CODE .. "\n	" .. key .. " = " .. "'".. tostring(value) .. "';" else -- Handle the string value
				CONFIGURATION_SOURCE_CODE = CONFIGURATION_SOURCE_CODE .. "\n	" .. key .. " = " .. tostring(value) .. ";"
			end
		end
	end
	for i = 1, #definedConfiguration.bannedPlayers do -- Handle the table value (banned players)
		if i == 1 then bannedPlayersStr = bannedPlayersStr .. "'" .. definedConfiguration.bannedPlayers[i] .. "'" else bannedPlayersStr = bannedPlayersStr .. ", '" .. definedConfiguration.bannedPlayers[i] .. "'" end
	end
	CONFIGURATION_SOURCE_CODE = CONFIGURATION_SOURCE_CODE .. "\n	--// Team Colors (By BrickColor)"
	for key, value in pairs(definedConfiguration) do -- Handle brick colors 
		if string.find(key, "TeamColor") and key ~= "groupTeamColor" then
			CONFIGURATION_SOURCE_CODE = CONFIGURATION_SOURCE_CODE .. "\n	" .. key .. " = " .. "BrickColor.new('" .. tostring(value) .. "');"
		elseif key == "groupTeamColor" then CONFIGURATION_SOURCE_CODE = CONFIGURATION_SOURCE_CODE .. "\n	" .. key .. " = " .. value .. ";"
		end
	end
	bannedPlayersStr = bannedPlayersStr .. "}"
	CONFIGURATION_SOURCE_CODE = CONFIGURATION_SOURCE_CODE .. "\n	--// Banned Players (By NAME or PLAYER ID)"
	CONFIGURATION_SOURCE_CODE = CONFIGURATION_SOURCE_CODE .. "\n	" .. bannedPlayersStr .. ";"
	CONFIGURATION_SOURCE_CODE = CONFIGURATION_SOURCE_CODE .. "\n}\nreturn configuration"
	warn(">>[SOURCE_CODE]: Done!")
end

function SET_VARS()
	definedConfiguration.groupId = WidgetObjects.setting_groupID:GetValue()
	definedConfiguration.groupTeamName = WidgetObjects.setting_groupName:GetValue()
	if WidgetObjects.setting_groupTeamColor:GetSelectedIndex() == 1 then
		definedConfiguration.groupTeamColor = "BrickColor.new('Black')"
	elseif WidgetObjects.setting_groupTeamColor:GetSelectedIndex() == 2 then
		definedConfiguration.groupTeamColor = "BrickColor.new('Blue')"
	elseif WidgetObjects.setting_groupTeamColor:GetSelectedIndex() == 3 then
		definedConfiguration.groupTeamColor = "BrickColor.new('Bright yellow')"
	elseif WidgetObjects.setting_groupTeamColor:GetSelectedIndex() == 4 then
		definedConfiguration.groupTeamColor = "BrickColor.new('Bright green')"
	elseif WidgetObjects.setting_groupTeamColor:GetSelectedIndex() == 5 then
		definedConfiguration.groupTeamColor = "BrickColor.new('White')"				
	end
	definedConfiguration.adminRank = WidgetObjects.setting_adminRank:GetValue()
	definedConfiguration.autoTeam = WidgetObjects.setting_autoTeam:GetValue()
	definedConfiguration.allowRandoms = WidgetObjects.setting_allowRandoms:GetValue()
	definedConfiguration.totalTime = tonumber(WidgetObjects.setting_totalTime:GetValue())
	definedConfiguration.raidingTime = tonumber(WidgetObjects.setting_raidTime:GetValue())
	definedConfiguration.raidersNeeded = tonumber(WidgetObjects.setting_raidersNeeded:GetValue())
	definedConfiguration.groupMembersNeeded = tonumber(WidgetObjects.setting_defendersNeeded:GetValue())
	definedConfiguration.terminalPart = WidgetObjects.setting_terminalPart:GetValue()
	definedConfiguration.auto_update = WidgetObjects.setting_auto_update:GetValue()
	definedConfiguration.autoTeam = WidgetObjects.setting_autoTeam:GetValue()
end

function INJECT_TERMINAL()
	warn("Cmn65's Raiding Terminal is being injected into the game... Two steps (BUILD/INJECT) will occur. BUILD will check your configuration, INJECT will download and place the terminal and then write the configuration file. I will let you know when we are done! ")
	warn(">> [BUILD]: Checking to make sure configuration values are of correct type...")
	--// Run through config and check for errors
	local prebuild = true
	local check1 = {WidgetObjects.setting_groupID, WidgetObjects.setting_adminRank, WidgetObjects.setting_totalTime, WidgetObjects.setting_raidTime, WidgetObjects.setting_raidersNeeded, WidgetObjects.setting_defendersNeeded} --#
	
	for i = 1, #check1 do
		if tonumber(check1[i]:GetValue()) == nil then
			check1[i]:SetValue("ERROR: Must be a NUMBER")
			prebuild = false
		else
			if tonumber(check1[i]:GetValue()) <= 0 then
				check1[i]:SetValue("ERROR: Must be greater than 0")
				prebuild = false
			end
		end
	end
	
	if prebuild == false then error("[BUILD]: Failed") else
		--// Backup old terminal (if there is one...)
		warn(">>[BUILD]: Success... moving to injection (this is the real bug step)")
		warn(">>[INJECT]: Checking for previously configured terminals...")
		if game.ServerScriptService:FindFirstChild("Cmn65's Raiding Terminal") then
			warn(">>[INJECT]: There is already an instance of Cmn65's Raiding Terminal! Disabling and moving into storage in game.ServerStorage.TerminalBackups.")
			if game.StarterGui:FindFirstChild("Cmn65's Raiding Terminal Gui") then game.StarterGui:FindFirstChild("Cmn65's Raiding Terminal Gui").Parent = game.ServerScriptService:FindFirstChild("Cmn65's Raiding Terminal") end
			if game.ServerStorage:FindFirstChild("TerminalBackups") then
				game.ServerScriptService:FindFirstChild("Cmn65's Raiding Terminal").Disabled = true
				game.ServerScriptService:FindFirstChild("Cmn65's Raiding Terminal").Parent = game.ServerStorage.TerminalBackups
			else
				Instance.new("Folder", game.ServerStorage).Name = "TerminalBackups"
				game.ServerScriptService:FindFirstChild("Cmn65's Raiding Terminal").Disabled = true
				game.ServerScriptService:FindFirstChild("Cmn65's Raiding Terminal").Parent = game.ServerStorage.TerminalBackups
			end
		end
		
		--// Insert new updated Terminal
		warn(">>[INJECT]: Downloading latest version of the terminal...")
		local newModel = game:GetService("InsertService"):LoadAsset(4879413218)
		warn(">>[INJECT]: Checking for correct contents...")
		if newModel:FindFirstChild("Cmn65's Raiding Terminal") == nil or newModel:FindFirstChild("Cmn65's Raiding Terminal Gui") == nil then error("[INJECT]: Failed - Could not find expected contents. This is usually due to a mis-match in naming. PM Cmn65 to get this resolved!") end
		local terminal = newModel:FindFirstChild("Cmn65's Raiding Terminal")
		local gui = newModel:FindFirstChild("Cmn65's Raiding Terminal Gui")
		warn(">>[INJECT]: Moving things into position!")
		gui.Parent = game.StarterGui
		terminal.Parent = game.ServerScriptService
		warn(">>[INJECT]: Attempting to write to contents of terminal.Configuration. This is where the fun begins...")
		terminal.Configuration:Destroy()
		local configModule = Instance.new("ModuleScript", terminal)
		configModule.Name = "Configuration"
		SET_VARS()
		BUILD_SOURCE_CODE()
		configModule.Source = CONFIGURATION_SOURCE_CODE
		CONFIGURATION_SOURCE_CODE = "--// Cmn65's Raiding Terminal\n-->> Configuration File\n-->> Edit this file to your needs and then have fun raiding!!\n\n-- See Documentation/Install for more detailed information\n\n-->> This configuration file as generated by the plugin! Make sure the configuration file is correct! \n\n\n\nlocal configuration = {"
		warn(">>[INJECT]: Configuration module generated and placed into the terminal script.")
		warn(">>[INJECT]: You are READY! Please make sure you proof read your configuration script to make sure it is correct! Press the Open Configuration button in the plugins menu to see your current configuration!")
		print(">>Cleaning up...")
		newModel:Destroy()
		warn("Cmn65's Raidign Terminal is ready for use! Thank you very much for using, and please PM me with any bugs concerning this plugin or the model itself! Or tweet @roblox_cmn65!")
	end
end
WidgetObjects.InjectTerminalButton:GetButton().MouseButton1Click:connect(INJECT_TERMINAL)

function removeTerminal()
	if game.ServerScriptService:FindFirstChild("Cmn65's Raiding Terminal") then
		game.ServerScriptService:FindFirstChild("Cmn65's Raiding Terminal"):Destroy()
	end
	if game.StarterGui:FindFirstChild("Cmn65's Raiding Terminal Gui") then
		game.StarterGui:FindFirstChild("Cmn65's Raiding Terminal Gui"):Destroy()
	end
end
WidgetObjects.RemoveTerminalButton:GetButton().MouseButton1Click:connect(removeTerminal)
